oeo-model:
 - src/ontology/edits/oeo-model.omn

oeo-physical:
 - src/ontology/edits/oeo-physical.omn

oeo-social:
 - src/ontology/edits/oeo-social.omn

oeo.omn:
 - src/ontology/oeo.omn

oeo-shared:
 - src/ontology/edits/oeo-shared.omn
 
external ontology:
  - src/ontology/modules/*
