dist: bionic
language: java

before_script:
  - mkdir $TRAVIS_BUILD_DIR/.logs
  - mkdir lib
  - wget https://github.com/ontodev/robot/releases/download/v1.6.0/robot.jar -O lib/robot.jar
  - TRAVIS_BASE=`pwd`
 
script:
  - cd $TRAVIS_BUILD_DIR
  - java -jar $TRAVIS_BASE/lib/robot.jar merge --input src/ontology/oeo.omn annotate --ontology-iri http://openenergy-platform.org/ontology/oeo/ --output results/merged.owl --output merged.owl > .logs/merge.txt
  - java -jar $TRAVIS_BASE/lib/robot.jar validate-profile --input merged.owl --profile Full -vvv --output merged-validation.txt > .logs/validate.txt
  - java -jar $TRAVIS_BASE/lib/robot.jar verify --input merged.owl --queries tests/verify/* > .logs/verify.log


after_failure:
  - more .log/* | cat